import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="keywords"
          content="nextjs, huntingcoder blog, hunting coder"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src='/sc.js' strategy="lazyOnload"></Script> */}

      <main className={styles.main}>
       
        <div className={styles.imagewrap}>
          {/* <Image className={styles.myImg} src="/images.jpg" width={237} height={158}/> */}
          <img
            src="/images.jpg"
            className={styles.myImg}
            width={237}
            height={158}
            alt="img coding"
          />
           <h1 className={styles.title}>
          <span className="dummy">&lt;HuntingCoder/&gt;</span>
        </h1>
        </div>
        <p className={styles.description}>
          A blog for hunting coders by a hunting coder Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut nesciunt error deleniti voluptatem accusantium tempore unde porro, culpa eos iste, eum, illo quod?
        </p>

        {/* <div className={`${styles1.con} ${styles2.con}`}> */}
        <div>
          <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
