// import Head from 'next/head'

// import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'

// import Image from 'next/image'

// const inter = Inter({ subsets: ['latin'] })

// export default function Home() {
//   return (
//     <>
//     <style jsx>
//          {`
//           h2{
//             font-size: 38px;
//           }
//           h3{
//             font-size: 28px;
//           }
//          `}
//        </style>

//       <Head>
//         <title>Hunting coders</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
      
//       <main className={`${styles.main} ${inter.className}`}>
        
//       <h1 className={styles.title}>
//           <span className='dummy'>Hunting Coder</span>
        
//         </h1>
//         <div className={styles.imagewrap}> 
// <Image className={styles.myImg} src="/images.jpg" alt='n' width={237} height={158}/>
//         </div>
//         <p className={styles.description}>
//           A blog for hunting coders by a hunting coder
//         </p>
//         <div>
//         <h2>Popular Blogs</h2>
//         <div className="blogItem">
//           <h3>How to learn JavaScript in 2022?</h3>
//           <p>JavaScript is the language used to design logic for the web</p>
//         </div>
//         <div className="blogItem">
//           <h3>How to learn JavaScript in 2022?</h3>
//           <p>JavaScript is the language used to design logic for the web</p>
//         </div>
//         <div className="blogItem">
//           <h3>How to learn JavaScript in 2022?</h3>
//           <p>JavaScript is the language used to design logic for the web</p>
//         </div>
//       </div>

       
//       </main>
//     </>
//   )
// }


import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import Link from 'next/link'
import styles from '../styles/Home.module.css' 


export default function Home() {

  // console.log(styles)
  return (
    <div className={styles.container}>
       <style jsx>
         {`
          h2{
            font-size: 38px;
          }
          h3{
            font-size: 28px;
          }
         `}
       </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, huntingcoder blog, hunting coder" />
        <link rel="icon" href="/favicon.ico" /> 
      </Head>
      {/* <Script src='/sc.js' strategy="lazyOnload"></Script> */}
      
      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className='dummy'>Hunting Coder</span>
        
        </h1>
        <div className={styles.imagewrap}> 
<Image className={styles.myImg} src="/images.jpg" width={237} height={158}/>
        </div>
        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>

      {/* <div className={`${styles1.con} ${styles2.con}`}> */}
      <div>
        <h2>Popular Blogs</h2>
        <div className="blogItem">
          <h3>How to learn JavaScript in 2022?</h3>
          <p>JavaScript is the language used to design logic for the web</p>
        </div>
        <div className="blogItem">
          <h3>How to learn JavaScript in 2022?</h3>
          <p>JavaScript is the language used to design logic for the web</p>
        </div>
        <div className="blogItem">
          <h3>How to learn JavaScript in 2022?</h3>
          <p>JavaScript is the language used to design logic for the web</p>
        </div>
      </div>
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}